set(mri "${PCM_AUDIO_OUTPUT}.mri")
file(WRITE "${mri}" "create \"${PCM_AUDIO_OUTPUT}\"\naddlib \"${PCM_AUDIO_INPUT}\"\n")
foreach(runtime IN LISTS PCM_AUDIO_RUNTIMES)
    file(APPEND "${mri}" "addlib \"${runtime}\"\n")
endforeach()
file(APPEND "${mri}" "save\nend\n")
execute_process(COMMAND "${PCM_AUDIO_AR}" -M INPUT_FILE "${mri}" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Could not bundle the native audio runtime")
endif()
